Add method to run command with terminal widget
redhat-developer/intellij-common pull request #91
Opened 2021-07-29 13:01 UTC by lstocchi

Signed-off-by: Luca Stocchi <lstocchi@redhat.com>

2021-08-12 09:16 UTC, adietish commented on src/main/java/com/redhat/devtools/intellij/common/utils/ExecHelper.java
> +    }
Invoking `createLocalShellWidget` via reflection (apparently in order to catch both API variants) could be extracted to a separate method for improved clarity/isolation.

2021-08-12 09:46 UTC, adietish commented on src/main/java/com/redhat/devtools/intellij/common/utils/ExecHelper.java
> +      } catch (IllegalAccessException | InvocationTargetException | IOException ignored) {}
Should log if something goes wrong that throws an Exception

2021-08-12 12:14 UTC, adietish commented on src/main/java/com/redhat/devtools/intellij/common/utils/ExecHelper.java
> +    }
done this in my added commit

2021-08-12 12:15 UTC, adietish commented on src/main/java/com/redhat/devtools/intellij/common/utils/ExecHelper.java
> +      } catch (IllegalAccessException | InvocationTargetException | IOException ignored) {}
done this in my added commit

2021-08-23 13:17 UTC, jeffmaury requested changes
New methods do not allow to pass environment (proxy,...). So this will not work in all case. I think we should get:
- either continue with ShellTerminalWidget but then set the env (through commands)
- work with TerminalExecutionConsole which seems a better fit for processes

2021-08-23 14:17 UTC, adietish commented
> New methods do not allow to pass environment (proxy,...). So this will not work in all case. I think we should get:
> 
>     * either continue with ShellTerminalWidget but then set the env (through commands)

The env can be set via the `localTerminalCustomizer` extension point in the plugin that is using common. This extension point is called whenever a terminal is opened. The same approach is ex. used by PyTerminal: https://github.com/JetBrains/intellij-community/commit/5f703db7df7e0b56f4680582ec69144fed79d008#diff-e7a13dca77dfd45ba213dc20019ce39ae0e332e520de0ecb3ca32acd0f11ce54R59

2021-08-23 15:57 UTC, jeffmaury commented
Which is a terrible design: you are using a probably application scoped extension point to pass parameters to a method !!!!!

2021-08-23 20:05 UTC, adietish commented
> Which is a terrible design: you are using a probably application scoped extension point to pass parameters to a method !!!!!

I did not design it ;) that's what IJ provides for this sake as one can see in PyTerminal. On the other hand one could argue that being able to pass specific env vars to a method is rather weird. As in bash, those exist for all processes that are run in that shell, not just for a single programm.

2021-08-23 20:49 UTC, jeffmaury commented
What we are looking is to launch a process and dump the output in a terminal window. The ShellTerminalWidget is designed to manage a system shell and the Python plugin extension point is here to inject the virtualenv environment. In our case, the environment is more dynamic (relative to the cluster URL) that's why TerminalExecutionConsole seems better suited

2021-09-24 15:05 UTC, lstocchi commented
I abandoned this solution as there is no easy way to set up envs.
Setting them within the command is not acceptable for me as the command is printed to the user and it would be a mess.
The only way i found out is https://github.com/redhat-developer/intellij-common/pull/91/files#diff-d6b49f55590165bc437c8ca2b4a64cf02851cb4a094f262f23749caf94e7758cR523 but it's a bit hacky and not reliable at all because if there are two consecutive calls there is the risk the envs will be overwritten.
So either we accept this risk or we add this method for ppl who wants to only run commands that do not require setting up envs. Otherwise it is not an option.

2021-10-06 10:44 UTC, lstocchi commented
Closing it as https://github.com/redhat-developer/intellij-common/pull/108 was chosen as the final solution

2021-10-06 10:44 UTC, closed without merging